### ISSUE TITLE
Page header text is cut on mobile devices

### ISSUE THREAD

**Issue by ch0rus** [lerra/lezg.in#2]
When visiting the site with a mobile browser the header text is cut. This is totally unacceptable.

On my device the header is shown as "Lezgin Bakircioglu - I m..."

Please help!

Attaching a screenshot showing the issue
![Screenshot_2020-10-23-23-46-10-806_com android chrome](https://user-images.githubusercontent.com/4912524/97056942-72c33d00-158a-11eb-9e9f-b64119be88b0.jpg)

**Comment by lerra** [comment]
fixed

**Comment by ch0rus** [comment]
Now it's perfect, thank you!
